// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace GamesStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221110093357_Add Identity Tables")]
    partial class AddIdentityTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.ConsoleDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsoleDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Xbox360"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PS3"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PS4"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PS5"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Xbox"
                        });
                });

            modelBuilder.Entity("Entities.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ConsoleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsoleId = 2,
                            Description = "A Japanese horror game series and a media franchise created by Capcom. It consists of survival horro, third-person shooter ad first-person shooter games, with players typically surviving in environments filled with zombies and other creatures",
                            GenreId = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1575844261401-d69721eb5044?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cmVzaWRlbnQlMjBldmlsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "Resident Evil",
                            Price = 130.50m
                        },
                        new
                        {
                            Id = 2,
                            ConsoleId = 4,
                            Description = "From a galaxy far, far away comes action and adventure with the heroes and villians of Star Wars. Master the art of starfighter combat in the authentic piloting experience. Master your hero's journey and play through massive battles across iconic locations in all three cinematic eras",
                            GenreId = 7,
                            ImageUrl = "https://images.unsplash.com/flagged/photo-1589829482673-03413c918c48?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8c3RhciUyMHdhcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Star Wars",
                            Price = 100.75m
                        },
                        new
                        {
                            Id = 3,
                            ConsoleId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1563506644863-444710df1e03?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fG5iYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "NBA 2K",
                            Price = 130.50m
                        },
                        new
                        {
                            Id = 27,
                            ConsoleId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1622643048696-883eafe4d8dc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8d2l0Y2hlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "The Witcher 3",
                            Price = 90.50m
                        },
                        new
                        {
                            Id = 4,
                            ConsoleId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1602901248692-06c8935adac0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Y2FsbCUyMG9mJTIwZHV0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "Call of Duty",
                            Price = 150.50m
                        },
                        new
                        {
                            Id = 5,
                            ConsoleId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1612404819070-77c6da472e68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8d2FyY3JhZnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Warcraft",
                            Price = 80.20m
                        },
                        new
                        {
                            Id = 6,
                            ConsoleId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1640079421264-61f50d89a736?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bWluZWNyYWZ0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "Minecraft",
                            Price = 200.50m
                        },
                        new
                        {
                            Id = 7,
                            ConsoleId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1624085568108-36410cfe4d24?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGdyYW5kJTIwdGhlZnQlMjBhdXRvfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "Grand Theft Auto",
                            Price = 120.55m
                        },
                        new
                        {
                            Id = 8,
                            ConsoleId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1496252223350-db9ad24b108c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dGhlJTIwc2ltc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "The Sims",
                            Price = 90.50m
                        },
                        new
                        {
                            Id = 9,
                            ConsoleId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1630713079609-4356d4106410?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8d2FyY3JhZnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Age of Empires",
                            Price = 130.75m
                        },
                        new
                        {
                            Id = 10,
                            ConsoleId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1638451490307-80b960906103?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8d2FyY3JhZnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Command & Conquer",
                            Price = 100.25m
                        },
                        new
                        {
                            Id = 11,
                            ConsoleId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1598776454302-94acd47baaa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c2hvb3RpbmclMjBnYW1lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "DOOM",
                            Price = 120.50m
                        },
                        new
                        {
                            Id = 12,
                            ConsoleId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1620231150904-a86b9802656a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Y2FsbCUyMG9mJTIwZHV0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "Half-life",
                            Price = 120.30m
                        },
                        new
                        {
                            Id = 13,
                            ConsoleId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1621364525332-f9c381f3bfe8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Y2FsbCUyMG9mJTIwZHV0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "Gears of War",
                            Price = 90.50m
                        },
                        new
                        {
                            Id = 14,
                            ConsoleId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1621886289899-6e78c8f379b0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8Y2FsbCUyMG9mJTIwZHV0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "The Division",
                            Price = 60.50m
                        },
                        new
                        {
                            Id = 15,
                            ConsoleId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1612212909979-5f9128008f87?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fGNhbGwlMjBvZiUyMGR1dHl8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Halo",
                            Price = 170.40m
                        },
                        new
                        {
                            Id = 16,
                            ConsoleId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1521252879211-999820594c75?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHJvbGUlMjBwbGF5aW5nJTIwZ2FtZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Skyrim",
                            Price = 220.50m
                        },
                        new
                        {
                            Id = 17,
                            ConsoleId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1484608577325-c7540cc6794d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGZhbGxvdXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Fallout 4",
                            Price = 115.50m
                        },
                        new
                        {
                            Id = 18,
                            ConsoleId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1624432105547-898636528f55?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGdyYW5kJTIwdGhlZnQlMjBhdXRvfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "Forza Motorsport",
                            Price = 300.50m
                        },
                        new
                        {
                            Id = 19,
                            ConsoleId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1598121876853-82437626c783?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8bWVzc2l8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "FIFA 2023",
                            Price = 320.50m
                        },
                        new
                        {
                            Id = 20,
                            ConsoleId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1522778034537-20a2486be803?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cm9uYWxkb3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "FIFA 2022",
                            Price = 280.50m
                        },
                        new
                        {
                            Id = 21,
                            ConsoleId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1652718425243-8fb1512f4026?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8YXNzYXNpbiUyMGNyZWVkfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
                            Name = "Assassin's Creed",
                            Price = 120.50m
                        },
                        new
                        {
                            Id = 22,
                            ConsoleId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 7,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1661901234139-d833950e05e0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fGd1bnN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Monkey Island",
                            Price = 220.50m
                        },
                        new
                        {
                            Id = 23,
                            ConsoleId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1602901248692-06c8935adac0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGd1bnN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Watch Dogs",
                            Price = 270.50m
                        },
                        new
                        {
                            Id = 24,
                            ConsoleId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1519669556878-63bdad8a1a49?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Z2FtZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Titanfall",
                            Price = 90.50m
                        },
                        new
                        {
                            Id = 25,
                            ConsoleId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1543844481-52e5d6b93760?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Z29kJTIwb2YlMjB3YXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "The Long Dark",
                            Price = 200.50m
                        },
                        new
                        {
                            Id = 26,
                            ConsoleId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmud tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur.",
                            GenreId = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1608744221958-a842da518d01?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Z29kJTIwb2YlMjB3YXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
                            Name = "Don't Starve",
                            Price = 190.50m
                        });
                });

            modelBuilder.Entity("Entities.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A game that simulates the practice of sports. Some games emphasize actually playing the sport, whilst others emphasize strategy and sport management",
                            Name = "Simulation and Sports"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A video game genre in which the player participates in a racing competition. They are distributed along a spectrum between more realistic racing simulations and more fantastical arcade-style racing games",
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "In these games, players often have less concrete goals and narrative pathways to pursue. Instead of beating the boss and saving the princess, you may face a variety of tasks you can accomplish in a number of different ways. This draws players into more immersive experiences, encouraging experimantation with what may be unfamiliar mechanics",
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Players control different factions and compete against each other simultaneously in 'real-time' hence the term 'real-time strategy'",
                            Name = "Real-time strategy"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The shooter is a long standing genre that developed several early offshoots and branched out into two primary sub-genres: the first person(FPS) and third-person(TPS).",
                            Name = "Shooter(FPS and TPS)"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The basic premise of the role playing game is simple and ubiquitious in numerous games: you create or take control of a character that you can then level up through experience points",
                            Name = "Role-playing games"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Among the earliest recognizable hybrid genres, action-adventure games have a deep focus on plot and combat through story involvement and tight gameplay mechanics",
                            Name = "Action-adventure"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The core mechanics of a survival game centers on resource management, often incorporating crafting or salvage systems that you can use to help keep your character alive. Horror is an even broader category, arguably encompassing dozens of survival titles. Almost anything with zombies, a post-apocalyptic storyline, or loads of jump scares is considered horror",
                            Name = "Survival and Horror"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Game", b =>
                {
                    b.HasOne("Entities.Models.ConsoleDevice", "ConsoleDevice")
                        .WithMany("Games")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsoleDevice");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.ConsoleDevice", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Entities.Models.Genre", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
